export const FETCH_STATES_DATA="FETCH_STATES_DATA";
export const FETCH_STATES_SUCCESS="FETCH_STATES_SUCCESS"
export const FETCH_STATES_ERROR="FETCH_STATES_ERROR";
export const ADD_NEW_STATE = 'ADD_NEW_STATE';
export const UPDATE_STATE = 'UPDATE_STATE';
